site_name: alchy
site_description: Enhancement library for SQLAlchemy
site_author: Derrick Gilland
repo_url: https://github.com/dgilland/alchy

pages:
  - [index.md, Home]
  - [model.md, Model]
  - [events.md, Events]
  - [query.md, Query]
  - [search.md, Search]
  - [manager.md, Manager]
theme: flatly

google_analytics: ['UA-50789401-1', 'dgilland.github.io']
